%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: G:\My Drive\Rat\SynergyControl\Data\Abnormal Gait Profiles\18-05-03_001_HE_SPZOO5#.xlsx
%    Worksheet: 3D
%
% Auto-generated by MATLAB on 07-Jan-2020 14:29:41

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 35);

% Specify sheet and range
opts.Sheet = "3D";
 opts.DataRange = "A1:AI680";

% Specify column names and types
opts.VariableNames = ["Time", "TDLO", "MPelantemed1X", "MPelantemed1Y", "MPelantemed1Z", "MPelantelat1X", "MPelantelat1Y", "MPelantelat1Z", "MPelpostmed1X", "MPelpostmed1Y", "MPelpostmed1Z", "MPelpostlat1X", "MPelpostlat1Y", "MPelpostlat1Z", "HipX", "HipY", "HipZ", "MFempost1X", "MFempost1Y", "MFempost1Z", "MFemante1X", "MFemante1Y", "MFemante1Z", "KneeX", "KneeY", "KneeZ", "MTibpost1X", "MTibpost1Y", "MTibpost1Z", "MTibante1X", "MTibante1Y", "MTibante1Z", "AnkleX", "AnkleY", "AnkleZ"];
opts.SelectedVariableNames = ["Time", "TDLO", "MPelantemed1X", "MPelantemed1Y", "MPelantemed1Z", "MPelantelat1X", "MPelantelat1Y", "MPelantelat1Z", "MPelpostmed1X", "MPelpostmed1Y", "MPelpostmed1Z", "MPelpostlat1X", "MPelpostlat1Y", "MPelpostlat1Z", "HipX", "HipY", "HipZ", "MFempost1X", "MFempost1Y", "MFempost1Z", "MFemante1X", "MFemante1Y", "MFemante1Z", "KneeX", "KneeY", "KneeZ", "MTibpost1X", "MTibpost1Y", "MTibpost1Z", "MTibante1X", "MTibante1Y", "MTibante1Z", "AnkleX", "AnkleY", "AnkleZ"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Setup rules for import
opts = setvaropts(opts, [1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35], "FillValue", 0);

% Import the data
tbl = readtable([fileparts(mfilename('fullpath')),'\Data\Abnormal Gait Profiles\18-05-18_005_HE_SPZOO6#.xlsx'], opts, "UseExcel", false);

%% Convert to output type
Time = tbl.Time;
TDLO = tbl.TDLO;
MPelantemed1X = tbl.MPelantemed1X;
MPelantemed1Y = tbl.MPelantemed1Y;
MPelantemed1Z = tbl.MPelantemed1Z;
MPelantelat1X = tbl.MPelantelat1X;
MPelantelat1Y = tbl.MPelantelat1Y;
MPelantelat1Z = tbl.MPelantelat1Z;
MPelpostmed1X = tbl.MPelpostmed1X;
MPelpostmed1Y = tbl.MPelpostmed1Y;
MPelpostmed1Z = tbl.MPelpostmed1Z;
MPelpostlat1X = tbl.MPelpostlat1X;
MPelpostlat1Y = tbl.MPelpostlat1Y;
MPelpostlat1Z = tbl.MPelpostlat1Z;
HipX = tbl.HipX;
HipY = tbl.HipY;
HipZ = tbl.HipZ;
MFempost1X = tbl.MFempost1X;
MFempost1Y = tbl.MFempost1Y;
MFempost1Z = tbl.MFempost1Z;
MFemante1X = tbl.MFemante1X;
MFemante1Y = tbl.MFemante1Y;
MFemante1Z = tbl.MFemante1Z;
KneeX = tbl.KneeX;
KneeY = tbl.KneeY;
KneeZ = tbl.KneeZ;
MTibpost1X = tbl.MTibpost1X;
MTibpost1Y = tbl.MTibpost1Y;
MTibpost1Z = tbl.MTibpost1Z;
MTibante1X = tbl.MTibante1X;
MTibante1Y = tbl.MTibante1Y;
MTibante1Z = tbl.MTibante1Z;
AnkleX = tbl.AnkleX;
AnkleY = tbl.AnkleY;
AnkleZ = tbl.AnkleZ;

%% Clear temporary variables
clear opts