function passive_tension_completer(infile)
    if contains(infile,'.asim')
        issim = 1;
    elseif contains(infile,'.aproj')
        issim = 0;
    else
        error('Input path neither .aproj nor .asim')
    end
    % For a given input infile (sim or proj) path, find the passive-tension AFORM and fill it with all muscle information in the infile
    intext = importdata(infile); 
    orgID = extractInfo(intext{find(contains(intext,'<Organism>'),1,'first')+2});
    if ~issim
        passfilename = char(extractBetween(string(intext{find(contains(intext,'&lt;Title&gt;PassiveTension'))+4}),'&gt;','&lt;'));
        passPath = [pwd,'\Animatlab\SynergyWalking\',passfilename];
        passtext = importdata(passPath);
        preamble = passtext(1:find(contains(passtext,'<AxisList>')));
        trailer = passtext(find(contains(passtext,'</AxisList>')):end);
    else
        temp1 = find(contains(intext,'<OutputFilename>PassiveTension'))+8;
        temp2 = find(contains(intext(temp1:end),'</DataColumns'),1,'first')+temp1-1;
        preamble = intext(1:temp1);
        trailer = intext(temp2:end);
    end
    
    muscInds = find(contains(intext,'<Type>LinearHillMuscle</Type>'))-3;
    numMuscs = length(muscInds);
    simMuscInfo = cell(numMuscs,2);
    dataInsert = {};
    for ii = 1:numMuscs
        % Name
        muscName = extractInfo(intext{muscInds(ii)+1});
        muscName = lower(muscName(4:end));
        % ID
        muscID = extractInfo(intext{muscInds(ii)+2});
        simMuscInfo{ii,1} = muscName;
        simMuscInfo{ii,2} = muscID;
        axisNum = ii - 1;
        if ~issim
            dataInsert = [dataInsert;axisMaker(muscName,muscID,axisNum,orgID)];
        else
            dataInsert = [dataInsert;columnMaker(muscName,muscID)];
        end
    end
    newPassive = [preamble;dataInsert;trailer];
    if ~issim
        fileID = fopen(passPath,'w');
    else
        fileID = fopen(infile,'w');
    end
    fprintf(fileID,'%s\n',newPassive{:});
    fclose(fileID);
    disp(['Passive tension file has been updated.'])
end
    function outChar = extractInfo(inLine)
        outChar = char(extractBetween(string(inLine),'>','<'));
    end

    function outFill = axisMaker(muscName,muscID,axisNum,orgID)
        %muscName = muscInfo{1}; muscID = muscInfo{2};
        outFill =  {'<Axis>';...
                    '<AssemblyFile>LicensedAnimatGUI.dll</AssemblyFile>';...
                    '<ClassName>LicensedAnimatGUI.DataObjects.Charting.Pro2DAxis</ClassName>';...
                    ['<Name>',muscName,'</Name>'];...
                    ['<WorkingAxis>',num2str(axisNum),'</WorkingAxis>'];...
                    '<DataColumns>';...
                    '<DataColumn>';...
                    '<AssemblyFile>LicensedAnimatGUI.dll</AssemblyFile>';...
                    '<ClassName>LicensedAnimatGUI.DataObjects.Charting.Pro2DColumn</ClassName>';...
                    ['<Name>',muscName,'</Name>'];...
                    ['<ID>',muscName,'-passive-dt</ID>'];...
                    '<DataItemAssemblyFile>AnimatGUI.dll</DataItemAssemblyFile>';...
                    '<DataItemClassName>AnimatGUI.DataObjects.Physical.Bodies.LinearHillMuscle</DataItemClassName>';...
                    ['<StructureID>',orgID,'</StructureID>'];...
                    ['<DataItemID>',muscID,'</DataItemID>'];...
                    '<SelectedDataType>Tension</SelectedDataType>';...
                    ['<DataSubSet>',num2str(axisNum),'</DataSubSet>'];...
                    ['<PrevDataSubset>',num2str(axisNum),'</PrevDataSubset>'];...
                    '<UseIncomingDataType>False</UseIncomingDataType>';...
                    '<LineType>MediumSolid</LineType>';...
                    '<PointType>Plus</PointType>';...
                    '<PlotMethodType>Line</PlotMethodType>';...
                    '<LineColor>-6139310</LineColor>';...
                    '</DataColumn>';...
                    '</DataColumns>';...
                    '</Axis>'};
    end
    
    function outFill = columnMaker(muscName,muscID)
        outFill =  {'<DataColumn>';...
                    '<ModuleName/>';...
                    '<Type>DataColumn</Type>';...
                    ['<ID>',muscName,'-passive-dt</ID>'];...
                    ['<ColumnName>',muscName,'</ColumnName>'];...
                    '<DataType>Tension</DataType>';...
                    ['<TargetID>',muscID,'</TargetID>'];...
                    '</DataColumn>'};
    end